### ISSUE TITLE
Implement a state pattern to control state of the game

### ISSUE THREAD

**Issue by aaronamk** [GDC-WM/2DGame2021#13]
Playing, paused, main menu, anything else we think of.

**Comment by BlastWind** [comment]
@Morenbarde Helpful resources: 
Must read to understand what's going on: 
1) https://gameprogrammingpatterns.com/state.html
Might be helpful: 
1) https://github.com/BlastWind/design_patterns_examples

Let me know if you want to schedule a call or something.
